#!/bin/bash -l
#SBATCH -J calculator_batch
#SBATCH -e calculator_error_%j
#SBATCH -o calculator_out_%j
#SBATCH -t 1:00:00
#SBATCH -n 1
#SBATCH -p serial
#SBATCH --mem=5000
#SBATCH --array=0,1,2,3,4,5,6,7,8,9,10,11,12,13

module load geoconda
python dryland_calculator.py $SLURM_ARRAY_TASK_ID